{% set version = '2020.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-turboem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/turboEM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/turboEM/turboEM_{{ version }}.tar.gz
  sha256: f5961873ed8a110704ca201a4d7d77e0f7423444365382b90e549d802b3d667c

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-doparallel
    - r-foreach
    - r-iterators
    - r-numderiv
    - r-quantreg
  run:
    - r-base
    - r-doparallel
    - r-foreach
    - r-iterators
    - r-numderiv
    - r-quantreg

test:
  commands:
    - $R -e "library('turboEM')"           # [not win]
    - "\"%R%\" -e \"library('turboEM')\""  # [win]

about:
  home: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
  license: GPL-2
  summary: Algorithms for accelerating the convergence of slow, monotone sequences from smooth,
    contraction mapping such as the EM and MM algorithms. It can be used to accelerate
    any smooth, linearly convergent acceleration scheme.  A tutorial style introduction
    to this package is available in a vignette on the CRAN download page or, when the
    package is loaded in an R session, with vignette("turboEM").
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: turboEM
# Title: A Suite of Convergence Acceleration Schemes for EM, MM and Other Fixed-Point Algorithms
# Description: Algorithms for accelerating the convergence of slow, monotone sequences from smooth, contraction mapping such as the EM and MM algorithms. It can be used to accelerate any smooth, linearly convergent acceleration scheme.  A tutorial style introduction to this package is available in a vignette on the CRAN download page or, when the package is loaded in an R session, with vignette("turboEM").
# Depends: R (>= 2.12.0), doParallel, foreach, numDeriv, quantreg
# Imports: iterators
# Suggests: setRNG
# Version: 2020.1
# LazyLoad: yes
# License: GPL-2
# Author: Jennifer F. Bobb [aut], Ravi Varadhan [aut, cre], Hui Zhao [ctb]
# Maintainer: Ravi Varadhan <ravi.varadhan@jhu.edu>
# Authors@R: c( person(given = c("Jennifer", "F."), family = "Bobb", role = "aut", email = "jbobb@hsph.harvard.edu"), person(given = "Ravi", family = "Varadhan", role = c("aut", "cre"), email = "ravi.varadhan@jhu.edu"), person(given = "Hui", family = "Zhao", role = "ctb"))
# URL: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
# Repository: CRAN
# Packaged: 2020-01-13 15:33:58 UTC; rvaradh1
# NeedsCompilation: no
# Date/Publication: 2020-01-13 16:40:02 UTC
