appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: A/7zKXS7QhrNZE2yZLD+h4gLGu0zPJwwxmi2uQGhvsFAfhby5ukK1LB6/W02YOmsNSlr0yccKo8ki3fwRBxS8k47teRXvh93ppEbXRvkwVWfg4UYTAUEXffmr/Zyo6cVHWkWlsdzBElrBTc3JDrZucJRjkMwh6HREYXgQ6m/EIZVQrKkz08RIYzigakPZFeuE2CUte+2GFK+gRHXU6lulRlmevc5HMvgMpu2iotNSA9LAlNe6qSgY80+D/kBpB1PlTN8dEhOlOM8KHytwmRhkx4hMAspXadyudk6QX+R20bj4r49emHgq7aettSwEHI0SgFruXavhlbk5n8yJ5ZwNqLQc7fHbnulrhgZZqtuLvsYHsSBG+ItIqXCT8CkAf5nC4ZXJhEynXL3WYOZV3zzWHRQLauPn6jAVNkH8Qv5WHHiEjL+aw6BFP9lmb6Y8eiSOKbssyRr5oDKfDoHY4TGm87LLIFMuJMPdGkqVlZ2yGqp1/cmbs7k3VRQOyFfgk6BEW0YtM3yrZmLLbrtkiVRPhSSf5yoIAIdJjSECz/D4zAFSyj75lRgpTGAFRqxRw65LZFQ1/7+WczcSnAFG0C7uo8ugj3Nza997G8yWNjs5rPuh9r4WHiJhfkSnkVr0X/aFYix/voexbDNn3PpmWlkxp+NJifZlAmAO1SzpcDDCgY=}
bot:
  automerge: true
